[package]
name = "rust-lambda-test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bootstrap"
path = "src/main.rs"

[dependencies]
lambda_runtime = "0.5.1"
serde_json = "1.0.79"
tokio = "1.18.0"
